name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to rollback to (e.g., v1, v2, v3)"
        required: true
        type: string

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Update ECS service with specific version
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: everfit-app-repo
          VERSION: ${{ github.event.inputs.version }}
        run: |
          aws ecs update-service \
            --cluster everfit-app-cluster \
            --service everfit-app-service \
            --task-definition everfit-app-task \
            --force-new-deployment \
            --query 'service.taskDefinition' \
            --output text
